# Change these first
owner: chequeado # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Chequeado
    url: https://www.chequeado.com
  - name: Chequeabot
    url: https://chequeabot.com
  - name: El abridor
    url: https://elabridor.chequeado.com/
  - name: test01
    url: https://tetst01.chequeabot.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  theme: dark
  baseUrl: /status
  logoUrl: https://chequeado.com/wp-content/themes/chequeado/assets/logos/svg/logo-chequeado-light.svg
  name: Upptime
  introTitle: "**Status de chequeado**"
  introMessage: Se visualiza el estado de todos los servicios en tiempo real.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
